name: Branch CI

on:
  push:
    branches:
      - main

jobs:
    nonprod-us-east-1:
        uses: ./.github/workflows/deployment-ci.yml
        secrets: inherit
        with:
            region: us-east-1
            account_number: 441058194263
            environment: nonprod
            account: snowman
            



