name: Branch CI

on:
  push:
    branches:
      - main


jobs:
  nonprod:
    uses: ./.github/workflows/deployment-template.yml
    secrets: inherit
    with:
      region: us-east-1
      account: snowman
      account_number: 441058194263
      environment: nonprod
