name: Deployment Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'Deployment environment (e.g., production, staging)'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy application
        run: |
          echo "Deploying to ${{ inputs.environment }}"
          # Add your deployment script or commands here
